# Generated by Django 3.0.3 on 2020-05-18 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200518_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='cart',
            new_name='orderCart',
        ),
    ]
